<?php


 function autoload_2e918f015cc2236a72c5548ba769a8cf($class)
{
    $classes = array(
        'Famoser\MBOApiWrapper\SaleService\Sale_x0020_Service' => __DIR__ .'/Sale_x0020_Service.php',
        'Famoser\MBOApiWrapper\SaleService\GetAcceptedCardType' => __DIR__ .'/GetAcceptedCardType.php',
        'Famoser\MBOApiWrapper\SaleService\GetAcceptedCardTypeRequest' => __DIR__ .'/GetAcceptedCardTypeRequest.php',
        'Famoser\MBOApiWrapper\SaleService\MBRequest' => __DIR__ .'/MBRequest.php',
        'Famoser\MBOApiWrapper\SaleService\SourceCredentials' => __DIR__ .'/SourceCredentials.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfInt' => __DIR__ .'/ArrayOfInt.php',
        'Famoser\MBOApiWrapper\SaleService\UserCredentials' => __DIR__ .'/UserCredentials.php',
        'Famoser\MBOApiWrapper\SaleService\XMLDetailLevel' => __DIR__ .'/XMLDetailLevel.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfString' => __DIR__ .'/ArrayOfString.php',
        'Famoser\MBOApiWrapper\SaleService\GetAcceptedCardTypeResponse' => __DIR__ .'/GetAcceptedCardTypeResponse.php',
        'Famoser\MBOApiWrapper\SaleService\GetAcceptedCardTypeResult' => __DIR__ .'/GetAcceptedCardTypeResult.php',
        'Famoser\MBOApiWrapper\SaleService\MBResult' => __DIR__ .'/MBResult.php',
        'Famoser\MBOApiWrapper\SaleService\StatusCode' => __DIR__ .'/StatusCode.php',
        'Famoser\MBOApiWrapper\SaleService\CheckoutShoppingCart' => __DIR__ .'/CheckoutShoppingCart.php',
        'Famoser\MBOApiWrapper\SaleService\CheckoutShoppingCartRequest' => __DIR__ .'/CheckoutShoppingCartRequest.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfCartItem' => __DIR__ .'/ArrayOfCartItem.php',
        'Famoser\MBOApiWrapper\SaleService\CartItem' => __DIR__ .'/CartItem.php',
        'Famoser\MBOApiWrapper\SaleService\MBObject' => __DIR__ .'/MBObject.php',
        'Famoser\MBOApiWrapper\SaleService\Site' => __DIR__ .'/Site.php',
        'Famoser\MBOApiWrapper\SaleService\ClassSchedule' => __DIR__ .'/ClassSchedule.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfClass' => __DIR__ .'/ArrayOfClass.php',
        'Famoser\MBOApiWrapper\SaleService\ClassCustom' => __DIR__ .'/ClassCustom.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfVisit' => __DIR__ .'/ArrayOfVisit.php',
        'Famoser\MBOApiWrapper\SaleService\Visit' => __DIR__ .'/Visit.php',
        'Famoser\MBOApiWrapper\SaleService\Staff' => __DIR__ .'/Staff.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfAppointment' => __DIR__ .'/ArrayOfAppointment.php',
        'Famoser\MBOApiWrapper\SaleService\Appointment' => __DIR__ .'/Appointment.php',
        'Famoser\MBOApiWrapper\SaleService\ScheduleItem' => __DIR__ .'/ScheduleItem.php',
        'Famoser\MBOApiWrapper\SaleService\Unavailability' => __DIR__ .'/Unavailability.php',
        'Famoser\MBOApiWrapper\SaleService\Availability' => __DIR__ .'/Availability.php',
        'Famoser\MBOApiWrapper\SaleService\SessionType' => __DIR__ .'/SessionType.php',
        'Famoser\MBOApiWrapper\SaleService\ActionCode' => __DIR__ .'/ActionCode.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfProgram' => __DIR__ .'/ArrayOfProgram.php',
        'Famoser\MBOApiWrapper\SaleService\Program' => __DIR__ .'/Program.php',
        'Famoser\MBOApiWrapper\SaleService\ScheduleType' => __DIR__ .'/ScheduleType.php',
        'Famoser\MBOApiWrapper\SaleService\Location' => __DIR__ .'/Location.php',
        'Famoser\MBOApiWrapper\SaleService\AppointmentStatus' => __DIR__ .'/AppointmentStatus.php',
        'Famoser\MBOApiWrapper\SaleService\Client' => __DIR__ .'/Client.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfClientIndex' => __DIR__ .'/ArrayOfClientIndex.php',
        'Famoser\MBOApiWrapper\SaleService\ClientIndex' => __DIR__ .'/ClientIndex.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfClientIndexValue' => __DIR__ .'/ArrayOfClientIndexValue.php',
        'Famoser\MBOApiWrapper\SaleService\ClientIndexValue' => __DIR__ .'/ClientIndexValue.php',
        'Famoser\MBOApiWrapper\SaleService\ClientCreditCard' => __DIR__ .'/ClientCreditCard.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfClientRelationship' => __DIR__ .'/ArrayOfClientRelationship.php',
        'Famoser\MBOApiWrapper\SaleService\ClientRelationship' => __DIR__ .'/ClientRelationship.php',
        'Famoser\MBOApiWrapper\SaleService\Relationship' => __DIR__ .'/Relationship.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfRep' => __DIR__ .'/ArrayOfRep.php',
        'Famoser\MBOApiWrapper\SaleService\Rep' => __DIR__ .'/Rep.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfSalesRep' => __DIR__ .'/ArrayOfSalesRep.php',
        'Famoser\MBOApiWrapper\SaleService\SalesRep' => __DIR__ .'/SalesRep.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfCustomClientField' => __DIR__ .'/ArrayOfCustomClientField.php',
        'Famoser\MBOApiWrapper\SaleService\CustomClientField' => __DIR__ .'/CustomClientField.php',
        'Famoser\MBOApiWrapper\SaleService\Liability' => __DIR__ .'/Liability.php',
        'Famoser\MBOApiWrapper\SaleService\ProspectStage' => __DIR__ .'/ProspectStage.php',
        'Famoser\MBOApiWrapper\SaleService\ClientService' => __DIR__ .'/ClientService.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfResource' => __DIR__ .'/ArrayOfResource.php',
        'Famoser\MBOApiWrapper\SaleService\Resource' => __DIR__ .'/Resource.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfUnavailability' => __DIR__ .'/ArrayOfUnavailability.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfAvailability' => __DIR__ .'/ArrayOfAvailability.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfLocation' => __DIR__ .'/ArrayOfLocation.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfProviderIDUpdate' => __DIR__ .'/ArrayOfProviderIDUpdate.php',
        'Famoser\MBOApiWrapper\SaleService\ProviderIDUpdate' => __DIR__ .'/ProviderIDUpdate.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfClient' => __DIR__ .'/ArrayOfClient.php',
        'Famoser\MBOApiWrapper\SaleService\ClassDescription' => __DIR__ .'/ClassDescription.php',
        'Famoser\MBOApiWrapper\SaleService\Level' => __DIR__ .'/Level.php',
        'Famoser\MBOApiWrapper\SaleService\Course' => __DIR__ .'/Course.php',
        'Famoser\MBOApiWrapper\SaleService\ShoppingCart' => __DIR__ .'/ShoppingCart.php',
        'Famoser\MBOApiWrapper\SaleService\Size' => __DIR__ .'/Size.php',
        'Famoser\MBOApiWrapper\SaleService\Color' => __DIR__ .'/Color.php',
        'Famoser\MBOApiWrapper\SaleService\Item' => __DIR__ .'/Item.php',
        'Famoser\MBOApiWrapper\SaleService\Tip' => __DIR__ .'/Tip.php',
        'Famoser\MBOApiWrapper\SaleService\Package' => __DIR__ .'/Package.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfService' => __DIR__ .'/ArrayOfService.php',
        'Famoser\MBOApiWrapper\SaleService\Service' => __DIR__ .'/Service.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfProduct' => __DIR__ .'/ArrayOfProduct.php',
        'Famoser\MBOApiWrapper\SaleService\Product' => __DIR__ .'/Product.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfLong' => __DIR__ .'/ArrayOfLong.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfPaymentInfo' => __DIR__ .'/ArrayOfPaymentInfo.php',
        'Famoser\MBOApiWrapper\SaleService\PaymentInfo' => __DIR__ .'/PaymentInfo.php',
        'Famoser\MBOApiWrapper\SaleService\GiftCardInfo' => __DIR__ .'/GiftCardInfo.php',
        'Famoser\MBOApiWrapper\SaleService\CheckInfo' => __DIR__ .'/CheckInfo.php',
        'Famoser\MBOApiWrapper\SaleService\CashInfo' => __DIR__ .'/CashInfo.php',
        'Famoser\MBOApiWrapper\SaleService\CompInfo' => __DIR__ .'/CompInfo.php',
        'Famoser\MBOApiWrapper\SaleService\TrackDataInfo' => __DIR__ .'/TrackDataInfo.php',
        'Famoser\MBOApiWrapper\SaleService\StoredCardInfo' => __DIR__ .'/StoredCardInfo.php',
        'Famoser\MBOApiWrapper\SaleService\EncryptedTrackDataInfo' => __DIR__ .'/EncryptedTrackDataInfo.php',
        'Famoser\MBOApiWrapper\SaleService\CustomPaymentInfo' => __DIR__ .'/CustomPaymentInfo.php',
        'Famoser\MBOApiWrapper\SaleService\DebitAccountInfo' => __DIR__ .'/DebitAccountInfo.php',
        'Famoser\MBOApiWrapper\SaleService\CreditCardInfo' => __DIR__ .'/CreditCardInfo.php',
        'Famoser\MBOApiWrapper\SaleService\CheckoutShoppingCartResponse' => __DIR__ .'/CheckoutShoppingCartResponse.php',
        'Famoser\MBOApiWrapper\SaleService\CheckoutShoppingCartResult' => __DIR__ .'/CheckoutShoppingCartResult.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfClassSchedule' => __DIR__ .'/ArrayOfClassSchedule.php',
        'Famoser\MBOApiWrapper\SaleService\GetSales' => __DIR__ .'/GetSales.php',
        'Famoser\MBOApiWrapper\SaleService\GetSalesRequest' => __DIR__ .'/GetSalesRequest.php',
        'Famoser\MBOApiWrapper\SaleService\GetSalesResponse' => __DIR__ .'/GetSalesResponse.php',
        'Famoser\MBOApiWrapper\SaleService\GetSalesResult' => __DIR__ .'/GetSalesResult.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfSale' => __DIR__ .'/ArrayOfSale.php',
        'Famoser\MBOApiWrapper\SaleService\Sale' => __DIR__ .'/Sale.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfPayment' => __DIR__ .'/ArrayOfPayment.php',
        'Famoser\MBOApiWrapper\SaleService\Payment' => __DIR__ .'/Payment.php',
        'Famoser\MBOApiWrapper\SaleService\GetServices' => __DIR__ .'/GetServices.php',
        'Famoser\MBOApiWrapper\SaleService\GetServicesRequest' => __DIR__ .'/GetServicesRequest.php',
        'Famoser\MBOApiWrapper\SaleService\GetServicesResponse' => __DIR__ .'/GetServicesResponse.php',
        'Famoser\MBOApiWrapper\SaleService\GetServicesResult' => __DIR__ .'/GetServicesResult.php',
        'Famoser\MBOApiWrapper\SaleService\UpdateServices' => __DIR__ .'/UpdateServices.php',
        'Famoser\MBOApiWrapper\SaleService\UpdateServicesRequest' => __DIR__ .'/UpdateServicesRequest.php',
        'Famoser\MBOApiWrapper\SaleService\UpdateServicesResponse' => __DIR__ .'/UpdateServicesResponse.php',
        'Famoser\MBOApiWrapper\SaleService\UpdateServicesResult' => __DIR__ .'/UpdateServicesResult.php',
        'Famoser\MBOApiWrapper\SaleService\GetPackages' => __DIR__ .'/GetPackages.php',
        'Famoser\MBOApiWrapper\SaleService\GetPackagesRequest' => __DIR__ .'/GetPackagesRequest.php',
        'Famoser\MBOApiWrapper\SaleService\GetPackagesResponse' => __DIR__ .'/GetPackagesResponse.php',
        'Famoser\MBOApiWrapper\SaleService\GetPackagesResult' => __DIR__ .'/GetPackagesResult.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfPackage' => __DIR__ .'/ArrayOfPackage.php',
        'Famoser\MBOApiWrapper\SaleService\GetProducts' => __DIR__ .'/GetProducts.php',
        'Famoser\MBOApiWrapper\SaleService\GetProductsRequest' => __DIR__ .'/GetProductsRequest.php',
        'Famoser\MBOApiWrapper\SaleService\GetProductsResponse' => __DIR__ .'/GetProductsResponse.php',
        'Famoser\MBOApiWrapper\SaleService\GetProductsResult' => __DIR__ .'/GetProductsResult.php',
        'Famoser\MBOApiWrapper\SaleService\UpdateProducts' => __DIR__ .'/UpdateProducts.php',
        'Famoser\MBOApiWrapper\SaleService\UpdateProductsRequest' => __DIR__ .'/UpdateProductsRequest.php',
        'Famoser\MBOApiWrapper\SaleService\UpdateProductsResponse' => __DIR__ .'/UpdateProductsResponse.php',
        'Famoser\MBOApiWrapper\SaleService\UpdateProductsResult' => __DIR__ .'/UpdateProductsResult.php',
        'Famoser\MBOApiWrapper\SaleService\RedeemSpaFinderWellnessCard' => __DIR__ .'/RedeemSpaFinderWellnessCard.php',
        'Famoser\MBOApiWrapper\SaleService\RedeemSpaFinderWellnessCardRequest' => __DIR__ .'/RedeemSpaFinderWellnessCardRequest.php',
        'Famoser\MBOApiWrapper\SaleService\RedeemSpaFinderWellnessCardResponse' => __DIR__ .'/RedeemSpaFinderWellnessCardResponse.php',
        'Famoser\MBOApiWrapper\SaleService\RedeemSpaFinderWellnessCardResult' => __DIR__ .'/RedeemSpaFinderWellnessCardResult.php',
        'Famoser\MBOApiWrapper\SaleService\GetCustomPaymentMethods' => __DIR__ .'/GetCustomPaymentMethods.php',
        'Famoser\MBOApiWrapper\SaleService\GetCustomPaymentMethodsRequest' => __DIR__ .'/GetCustomPaymentMethodsRequest.php',
        'Famoser\MBOApiWrapper\SaleService\GetCustomPaymentMethodsResponse' => __DIR__ .'/GetCustomPaymentMethodsResponse.php',
        'Famoser\MBOApiWrapper\SaleService\GetCustomPaymentMethodsResult' => __DIR__ .'/GetCustomPaymentMethodsResult.php',
        'Famoser\MBOApiWrapper\SaleService\ArrayOfCustomPaymentInfo' => __DIR__ .'/ArrayOfCustomPaymentInfo.php',
        'Famoser\MBOApiWrapper\SaleService\ReturnSale' => __DIR__ .'/ReturnSale.php',
        'Famoser\MBOApiWrapper\SaleService\ReturnSaleRequest' => __DIR__ .'/ReturnSaleRequest.php',
        'Famoser\MBOApiWrapper\SaleService\ReturnSaleResponse' => __DIR__ .'/ReturnSaleResponse.php',
        'Famoser\MBOApiWrapper\SaleService\ReturnSaleResult' => __DIR__ .'/ReturnSaleResult.php',
        'Famoser\MBOApiWrapper\SaleService\UpdateSaleDate' => __DIR__ .'/UpdateSaleDate.php',
        'Famoser\MBOApiWrapper\SaleService\UpdateSaleDateRequest' => __DIR__ .'/UpdateSaleDateRequest.php',
        'Famoser\MBOApiWrapper\SaleService\UpdateSaleDateResponse' => __DIR__ .'/UpdateSaleDateResponse.php',
        'Famoser\MBOApiWrapper\SaleService\UpdateSaleDateResult' => __DIR__ .'/UpdateSaleDateResult.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_2e918f015cc2236a72c5548ba769a8cf');

// Do nothing. The rest is just leftovers from the code generation.
{
}
