<?php


 function autoload_02d1fbee201b14a5ea8b8536d381cda1($class)
{
    $classes = array(
        'Famoser\MBOApiWrapper\FinderService\Finder_x0020_Service' => __DIR__ .'/Finder_x0020_Service.php',
        'Famoser\MBOApiWrapper\FinderService\GetClassesWithinRadius' => __DIR__ .'/GetClassesWithinRadius.php',
        'Famoser\MBOApiWrapper\FinderService\GetClassesWithinRadiusRequest' => __DIR__ .'/GetClassesWithinRadiusRequest.php',
        'Famoser\MBOApiWrapper\FinderService\MBRequest' => __DIR__ .'/MBRequest.php',
        'Famoser\MBOApiWrapper\FinderService\SourceCredentials' => __DIR__ .'/SourceCredentials.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfInt' => __DIR__ .'/ArrayOfInt.php',
        'Famoser\MBOApiWrapper\FinderService\UserCredentials' => __DIR__ .'/UserCredentials.php',
        'Famoser\MBOApiWrapper\FinderService\XMLDetailLevel' => __DIR__ .'/XMLDetailLevel.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfString' => __DIR__ .'/ArrayOfString.php',
        'Famoser\MBOApiWrapper\FinderService\GetClassesWithinRadiusResponse' => __DIR__ .'/GetClassesWithinRadiusResponse.php',
        'Famoser\MBOApiWrapper\FinderService\GetClassesWithinRadiusResult' => __DIR__ .'/GetClassesWithinRadiusResult.php',
        'Famoser\MBOApiWrapper\FinderService\MBResult' => __DIR__ .'/MBResult.php',
        'Famoser\MBOApiWrapper\FinderService\StatusCode' => __DIR__ .'/StatusCode.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfFinderClass' => __DIR__ .'/ArrayOfFinderClass.php',
        'Famoser\MBOApiWrapper\FinderService\FinderClass' => __DIR__ .'/FinderClass.php',
        'Famoser\MBOApiWrapper\FinderService\Organization' => __DIR__ .'/Organization.php',
        'Famoser\MBOApiWrapper\FinderService\Site' => __DIR__ .'/Site.php',
        'Famoser\MBOApiWrapper\FinderService\FinderSessionType' => __DIR__ .'/FinderSessionType.php',
        'Famoser\MBOApiWrapper\FinderService\ActionCode' => __DIR__ .'/ActionCode.php',
        'Famoser\MBOApiWrapper\FinderService\Location' => __DIR__ .'/Location.php',
        'Famoser\MBOApiWrapper\FinderService\MBObject' => __DIR__ .'/MBObject.php',
        'Famoser\MBOApiWrapper\FinderService\Resource' => __DIR__ .'/Resource.php',
        'Famoser\MBOApiWrapper\FinderService\ClientService' => __DIR__ .'/ClientService.php',
        'Famoser\MBOApiWrapper\FinderService\Program' => __DIR__ .'/Program.php',
        'Famoser\MBOApiWrapper\FinderService\ScheduleType' => __DIR__ .'/ScheduleType.php',
        'Famoser\MBOApiWrapper\FinderService\SalesRep' => __DIR__ .'/SalesRep.php',
        'Famoser\MBOApiWrapper\FinderService\Rep' => __DIR__ .'/Rep.php',
        'Famoser\MBOApiWrapper\FinderService\Staff' => __DIR__ .'/Staff.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfAppointment' => __DIR__ .'/ArrayOfAppointment.php',
        'Famoser\MBOApiWrapper\FinderService\Appointment' => __DIR__ .'/Appointment.php',
        'Famoser\MBOApiWrapper\FinderService\ScheduleItem' => __DIR__ .'/ScheduleItem.php',
        'Famoser\MBOApiWrapper\FinderService\Unavailability' => __DIR__ .'/Unavailability.php',
        'Famoser\MBOApiWrapper\FinderService\Availability' => __DIR__ .'/Availability.php',
        'Famoser\MBOApiWrapper\FinderService\SessionType' => __DIR__ .'/SessionType.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfProgram' => __DIR__ .'/ArrayOfProgram.php',
        'Famoser\MBOApiWrapper\FinderService\AppointmentStatus' => __DIR__ .'/AppointmentStatus.php',
        'Famoser\MBOApiWrapper\FinderService\Client' => __DIR__ .'/Client.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfClientIndex' => __DIR__ .'/ArrayOfClientIndex.php',
        'Famoser\MBOApiWrapper\FinderService\ClientIndex' => __DIR__ .'/ClientIndex.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfClientIndexValue' => __DIR__ .'/ArrayOfClientIndexValue.php',
        'Famoser\MBOApiWrapper\FinderService\ClientIndexValue' => __DIR__ .'/ClientIndexValue.php',
        'Famoser\MBOApiWrapper\FinderService\ClientCreditCard' => __DIR__ .'/ClientCreditCard.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfClientRelationship' => __DIR__ .'/ArrayOfClientRelationship.php',
        'Famoser\MBOApiWrapper\FinderService\ClientRelationship' => __DIR__ .'/ClientRelationship.php',
        'Famoser\MBOApiWrapper\FinderService\Relationship' => __DIR__ .'/Relationship.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfRep' => __DIR__ .'/ArrayOfRep.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfSalesRep' => __DIR__ .'/ArrayOfSalesRep.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfCustomClientField' => __DIR__ .'/ArrayOfCustomClientField.php',
        'Famoser\MBOApiWrapper\FinderService\CustomClientField' => __DIR__ .'/CustomClientField.php',
        'Famoser\MBOApiWrapper\FinderService\Liability' => __DIR__ .'/Liability.php',
        'Famoser\MBOApiWrapper\FinderService\ProspectStage' => __DIR__ .'/ProspectStage.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfResource' => __DIR__ .'/ArrayOfResource.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfUnavailability' => __DIR__ .'/ArrayOfUnavailability.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfAvailability' => __DIR__ .'/ArrayOfAvailability.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfLocation' => __DIR__ .'/ArrayOfLocation.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfProviderIDUpdate' => __DIR__ .'/ArrayOfProviderIDUpdate.php',
        'Famoser\MBOApiWrapper\FinderService\ProviderIDUpdate' => __DIR__ .'/ProviderIDUpdate.php',
        'Famoser\MBOApiWrapper\FinderService\GetSessionTypesWithinRadius' => __DIR__ .'/GetSessionTypesWithinRadius.php',
        'Famoser\MBOApiWrapper\FinderService\GetSessionTypesWithinRadiusRequest' => __DIR__ .'/GetSessionTypesWithinRadiusRequest.php',
        'Famoser\MBOApiWrapper\FinderService\GetSessionTypesWithinRadiusResponse' => __DIR__ .'/GetSessionTypesWithinRadiusResponse.php',
        'Famoser\MBOApiWrapper\FinderService\GetSessionTypesWithinRadiusResult' => __DIR__ .'/GetSessionTypesWithinRadiusResult.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfFinderAppointment' => __DIR__ .'/ArrayOfFinderAppointment.php',
        'Famoser\MBOApiWrapper\FinderService\FinderAppointment' => __DIR__ .'/FinderAppointment.php',
        'Famoser\MBOApiWrapper\FinderService\GetBusinessLocationsWithinRadius' => __DIR__ .'/GetBusinessLocationsWithinRadius.php',
        'Famoser\MBOApiWrapper\FinderService\GetBusinessLocationsWithinRadiusRequest' => __DIR__ .'/GetBusinessLocationsWithinRadiusRequest.php',
        'Famoser\MBOApiWrapper\FinderService\GetBusinessLocationsWithinRadiusResponse' => __DIR__ .'/GetBusinessLocationsWithinRadiusResponse.php',
        'Famoser\MBOApiWrapper\FinderService\GetBusinessLocationsWithinRadiusResult' => __DIR__ .'/GetBusinessLocationsWithinRadiusResult.php',
        'Famoser\MBOApiWrapper\FinderService\FinderCheckoutShoppingCart' => __DIR__ .'/FinderCheckoutShoppingCart.php',
        'Famoser\MBOApiWrapper\FinderService\FinderCheckoutShoppingCartRequest' => __DIR__ .'/FinderCheckoutShoppingCartRequest.php',
        'Famoser\MBOApiWrapper\FinderService\SpaFinderWellnessCard' => __DIR__ .'/SpaFinderWellnessCard.php',
        'Famoser\MBOApiWrapper\FinderService\PaymentInfo' => __DIR__ .'/PaymentInfo.php',
        'Famoser\MBOApiWrapper\FinderService\GiftCardInfo' => __DIR__ .'/GiftCardInfo.php',
        'Famoser\MBOApiWrapper\FinderService\CheckInfo' => __DIR__ .'/CheckInfo.php',
        'Famoser\MBOApiWrapper\FinderService\CashInfo' => __DIR__ .'/CashInfo.php',
        'Famoser\MBOApiWrapper\FinderService\CompInfo' => __DIR__ .'/CompInfo.php',
        'Famoser\MBOApiWrapper\FinderService\TrackDataInfo' => __DIR__ .'/TrackDataInfo.php',
        'Famoser\MBOApiWrapper\FinderService\StoredCardInfo' => __DIR__ .'/StoredCardInfo.php',
        'Famoser\MBOApiWrapper\FinderService\EncryptedTrackDataInfo' => __DIR__ .'/EncryptedTrackDataInfo.php',
        'Famoser\MBOApiWrapper\FinderService\CustomPaymentInfo' => __DIR__ .'/CustomPaymentInfo.php',
        'Famoser\MBOApiWrapper\FinderService\DebitAccountInfo' => __DIR__ .'/DebitAccountInfo.php',
        'Famoser\MBOApiWrapper\FinderService\CreditCardInfo' => __DIR__ .'/CreditCardInfo.php',
        'Famoser\MBOApiWrapper\FinderService\FinderCheckoutShoppingCartResponse' => __DIR__ .'/FinderCheckoutShoppingCartResponse.php',
        'Famoser\MBOApiWrapper\FinderService\FinderCheckoutShoppingCartResult' => __DIR__ .'/FinderCheckoutShoppingCartResult.php',
        'Famoser\MBOApiWrapper\FinderService\ShoppingCart' => __DIR__ .'/ShoppingCart.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfCartItem' => __DIR__ .'/ArrayOfCartItem.php',
        'Famoser\MBOApiWrapper\FinderService\CartItem' => __DIR__ .'/CartItem.php',
        'Famoser\MBOApiWrapper\FinderService\Item' => __DIR__ .'/Item.php',
        'Famoser\MBOApiWrapper\FinderService\Tip' => __DIR__ .'/Tip.php',
        'Famoser\MBOApiWrapper\FinderService\Package' => __DIR__ .'/Package.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfService' => __DIR__ .'/ArrayOfService.php',
        'Famoser\MBOApiWrapper\FinderService\Service' => __DIR__ .'/Service.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfProduct' => __DIR__ .'/ArrayOfProduct.php',
        'Famoser\MBOApiWrapper\FinderService\Product' => __DIR__ .'/Product.php',
        'Famoser\MBOApiWrapper\FinderService\Color' => __DIR__ .'/Color.php',
        'Famoser\MBOApiWrapper\FinderService\Size' => __DIR__ .'/Size.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfLong' => __DIR__ .'/ArrayOfLong.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfClass' => __DIR__ .'/ArrayOfClass.php',
        'Famoser\MBOApiWrapper\FinderService\ClassCustom' => __DIR__ .'/ClassCustom.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfVisit' => __DIR__ .'/ArrayOfVisit.php',
        'Famoser\MBOApiWrapper\FinderService\Visit' => __DIR__ .'/Visit.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfClient' => __DIR__ .'/ArrayOfClient.php',
        'Famoser\MBOApiWrapper\FinderService\ClassDescription' => __DIR__ .'/ClassDescription.php',
        'Famoser\MBOApiWrapper\FinderService\Level' => __DIR__ .'/Level.php',
        'Famoser\MBOApiWrapper\FinderService\AddOrUpdateFinderUsers' => __DIR__ .'/AddOrUpdateFinderUsers.php',
        'Famoser\MBOApiWrapper\FinderService\AddOrUpdateFinderUsersRequest' => __DIR__ .'/AddOrUpdateFinderUsersRequest.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfFinderUser' => __DIR__ .'/ArrayOfFinderUser.php',
        'Famoser\MBOApiWrapper\FinderService\FinderUser' => __DIR__ .'/FinderUser.php',
        'Famoser\MBOApiWrapper\FinderService\ArrayOfClientCreditCard' => __DIR__ .'/ArrayOfClientCreditCard.php',
        'Famoser\MBOApiWrapper\FinderService\AddOrUpdateFinderUsersResponse' => __DIR__ .'/AddOrUpdateFinderUsersResponse.php',
        'Famoser\MBOApiWrapper\FinderService\AddOrUpdateFinderUsersResult' => __DIR__ .'/AddOrUpdateFinderUsersResult.php',
        'Famoser\MBOApiWrapper\FinderService\GetFinderUser' => __DIR__ .'/GetFinderUser.php',
        'Famoser\MBOApiWrapper\FinderService\GetFinderUserRequest' => __DIR__ .'/GetFinderUserRequest.php',
        'Famoser\MBOApiWrapper\FinderService\GetFinderUserResponse' => __DIR__ .'/GetFinderUserResponse.php',
        'Famoser\MBOApiWrapper\FinderService\GetFinderUserResult' => __DIR__ .'/GetFinderUserResult.php',
        'Famoser\MBOApiWrapper\FinderService\SendFinderUserNewPassword' => __DIR__ .'/SendFinderUserNewPassword.php',
        'Famoser\MBOApiWrapper\FinderService\SendFinderUserNewPasswordRequest' => __DIR__ .'/SendFinderUserNewPasswordRequest.php',
        'Famoser\MBOApiWrapper\FinderService\SendFinderUserNewPasswordResponse' => __DIR__ .'/SendFinderUserNewPasswordResponse.php',
        'Famoser\MBOApiWrapper\FinderService\SendFinderUserNewPasswordResult' => __DIR__ .'/SendFinderUserNewPasswordResult.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_02d1fbee201b14a5ea8b8536d381cda1');

// Do nothing. The rest is just leftovers from the code generation.
{
}
