//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18010
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoverExplorer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Websites : global::System.Configuration.ApplicationSettingsBase {
        
        private static Websites defaultInstance = ((Websites)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Websites())));
        
        public static Websites Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.seekacover.com/")]
        public string website1 {
            get {
                return ((string)(this["website1"]));
            }
            set {
                this["website1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<li><img src=\"")]
        public string webseite1stelle1teil1 {
            get {
                return ((string)(this["webseite1stelle1teil1"]));
            }
            set {
                this["webseite1stelle1teil1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string webseite1stelle1teil2 {
            get {
                return ((string)(this["webseite1stelle1teil2"]));
            }
            set {
                this["webseite1stelle1teil2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\" title=\"")]
        public string webseite1stelle2teil1 {
            get {
                return ((string)(this["webseite1stelle2teil1"]));
            }
            set {
                this["webseite1stelle2teil1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" CD Covers\"></li>")]
        public string webseite1stelle2teil2 {
            get {
                return ((string)(this["webseite1stelle2teil2"]));
            }
            set {
                this["webseite1stelle2teil2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.seekacover.com/cd/")]
        public string website1search {
            get {
                return ((string)(this["website1search"]));
            }
            set {
                this["website1search"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string website1stelle1 {
            get {
                return ((string)(this["website1stelle1"]));
            }
            set {
                this["website1stelle1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string website1stelle2 {
            get {
                return ((string)(this["website1stelle2"]));
            }
            set {
                this["website1stelle2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string schlagworte {
            get {
                return ((string)(this["schlagworte"]));
            }
            set {
                this["schlagworte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string website1adresse {
            get {
                return ((string)(this["website1adresse"]));
            }
            set {
                this["website1adresse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.amazon.com/s/keywords=")]
        public string website2search {
            get {
                return ((string)(this["website2search"]));
            }
            set {
                this["website2search"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.amazon.com/")]
        public string website2 {
            get {
                return ((string)(this["website2"]));
            }
            set {
                this["website2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<div id=\"atfResults\" class=\"list results apsList\">")]
        public string website2stelle1teil1 {
            get {
                return ((string)(this["website2stelle1teil1"]));
            }
            set {
                this["website2stelle1teil1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string website2stelle1teil2 {
            get {
                return ((string)(this["website2stelle1teil2"]));
            }
            set {
                this["website2stelle1teil2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\" class=\"productImage\" alt=\"Product Details\"/></a></div>")]
        public string website2stelle2teil1 {
            get {
                return ((string)(this["website2stelle2teil1"]));
            }
            set {
                this["website2stelle2teil1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string website2stelle2teil2 {
            get {
                return ((string)(this["website2stelle2teil2"]));
            }
            set {
                this["website2stelle2teil2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string website2stelle1 {
            get {
                return ((string)(this["website2stelle1"]));
            }
            set {
                this["website2stelle1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string website2stelle2 {
            get {
                return ((string)(this["website2stelle2"]));
            }
            set {
                this["website2stelle2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string website2adresse {
            get {
                return ((string)(this["website2adresse"]));
            }
            set {
                this["website2adresse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.google.com/")]
        public string website3 {
            get {
                return ((string)(this["website3"]));
            }
            set {
                this["website3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.google.com/search?site=imghp&tbm=isch&source=hp&biw=1366&bih=667&q=")]
        public string website3search {
            get {
                return ((string)(this["website3search"]));
            }
            set {
                this["website3search"] = value;
            }
        }
    }
}
