<?php


 function autoload_8ff1164f949e3fd9aef489b1419e195f($class)
{
    $classes = array(
        'Famoser\MBOApiWrapper\AppointmentService\Appointment_x0020_Service' => __DIR__ .'/Appointment_x0020_Service.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetStaffAppointments' => __DIR__ .'/GetStaffAppointments.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetStaffAppointmentsRequest' => __DIR__ .'/GetStaffAppointmentsRequest.php',
        'Famoser\MBOApiWrapper\AppointmentService\MBRequest' => __DIR__ .'/MBRequest.php',
        'Famoser\MBOApiWrapper\AppointmentService\SourceCredentials' => __DIR__ .'/SourceCredentials.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfInt' => __DIR__ .'/ArrayOfInt.php',
        'Famoser\MBOApiWrapper\AppointmentService\UserCredentials' => __DIR__ .'/UserCredentials.php',
        'Famoser\MBOApiWrapper\AppointmentService\XMLDetailLevel' => __DIR__ .'/XMLDetailLevel.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfString' => __DIR__ .'/ArrayOfString.php',
        'Famoser\MBOApiWrapper\AppointmentService\StaffCredentials' => __DIR__ .'/StaffCredentials.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfLong' => __DIR__ .'/ArrayOfLong.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetStaffAppointmentsResponse' => __DIR__ .'/GetStaffAppointmentsResponse.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetStaffAppointmentsResult' => __DIR__ .'/GetStaffAppointmentsResult.php',
        'Famoser\MBOApiWrapper\AppointmentService\MBResult' => __DIR__ .'/MBResult.php',
        'Famoser\MBOApiWrapper\AppointmentService\StatusCode' => __DIR__ .'/StatusCode.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfAppointment' => __DIR__ .'/ArrayOfAppointment.php',
        'Famoser\MBOApiWrapper\AppointmentService\Appointment' => __DIR__ .'/Appointment.php',
        'Famoser\MBOApiWrapper\AppointmentService\ScheduleItem' => __DIR__ .'/ScheduleItem.php',
        'Famoser\MBOApiWrapper\AppointmentService\MBObject' => __DIR__ .'/MBObject.php',
        'Famoser\MBOApiWrapper\AppointmentService\Site' => __DIR__ .'/Site.php',
        'Famoser\MBOApiWrapper\AppointmentService\Resource' => __DIR__ .'/Resource.php',
        'Famoser\MBOApiWrapper\AppointmentService\ActionCode' => __DIR__ .'/ActionCode.php',
        'Famoser\MBOApiWrapper\AppointmentService\ClientService' => __DIR__ .'/ClientService.php',
        'Famoser\MBOApiWrapper\AppointmentService\Program' => __DIR__ .'/Program.php',
        'Famoser\MBOApiWrapper\AppointmentService\ScheduleType' => __DIR__ .'/ScheduleType.php',
        'Famoser\MBOApiWrapper\AppointmentService\SalesRep' => __DIR__ .'/SalesRep.php',
        'Famoser\MBOApiWrapper\AppointmentService\Rep' => __DIR__ .'/Rep.php',
        'Famoser\MBOApiWrapper\AppointmentService\Staff' => __DIR__ .'/Staff.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfUnavailability' => __DIR__ .'/ArrayOfUnavailability.php',
        'Famoser\MBOApiWrapper\AppointmentService\Unavailability' => __DIR__ .'/Unavailability.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfAvailability' => __DIR__ .'/ArrayOfAvailability.php',
        'Famoser\MBOApiWrapper\AppointmentService\Availability' => __DIR__ .'/Availability.php',
        'Famoser\MBOApiWrapper\AppointmentService\SessionType' => __DIR__ .'/SessionType.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfProgram' => __DIR__ .'/ArrayOfProgram.php',
        'Famoser\MBOApiWrapper\AppointmentService\Location' => __DIR__ .'/Location.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfLocation' => __DIR__ .'/ArrayOfLocation.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfProviderIDUpdate' => __DIR__ .'/ArrayOfProviderIDUpdate.php',
        'Famoser\MBOApiWrapper\AppointmentService\ProviderIDUpdate' => __DIR__ .'/ProviderIDUpdate.php',
        'Famoser\MBOApiWrapper\AppointmentService\ClientRelationship' => __DIR__ .'/ClientRelationship.php',
        'Famoser\MBOApiWrapper\AppointmentService\Client' => __DIR__ .'/Client.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfClientIndex' => __DIR__ .'/ArrayOfClientIndex.php',
        'Famoser\MBOApiWrapper\AppointmentService\ClientIndex' => __DIR__ .'/ClientIndex.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfClientIndexValue' => __DIR__ .'/ArrayOfClientIndexValue.php',
        'Famoser\MBOApiWrapper\AppointmentService\ClientIndexValue' => __DIR__ .'/ClientIndexValue.php',
        'Famoser\MBOApiWrapper\AppointmentService\ClientCreditCard' => __DIR__ .'/ClientCreditCard.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfClientRelationship' => __DIR__ .'/ArrayOfClientRelationship.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfRep' => __DIR__ .'/ArrayOfRep.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfSalesRep' => __DIR__ .'/ArrayOfSalesRep.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfCustomClientField' => __DIR__ .'/ArrayOfCustomClientField.php',
        'Famoser\MBOApiWrapper\AppointmentService\CustomClientField' => __DIR__ .'/CustomClientField.php',
        'Famoser\MBOApiWrapper\AppointmentService\Liability' => __DIR__ .'/Liability.php',
        'Famoser\MBOApiWrapper\AppointmentService\ProspectStage' => __DIR__ .'/ProspectStage.php',
        'Famoser\MBOApiWrapper\AppointmentService\Relationship' => __DIR__ .'/Relationship.php',
        'Famoser\MBOApiWrapper\AppointmentService\AppointmentStatus' => __DIR__ .'/AppointmentStatus.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfResource' => __DIR__ .'/ArrayOfResource.php',
        'Famoser\MBOApiWrapper\AppointmentService\AddOrUpdateAppointments' => __DIR__ .'/AddOrUpdateAppointments.php',
        'Famoser\MBOApiWrapper\AppointmentService\AddOrUpdateAppointmentsRequest' => __DIR__ .'/AddOrUpdateAppointmentsRequest.php',
        'Famoser\MBOApiWrapper\AppointmentService\AddOrUpdateAppointmentsResponse' => __DIR__ .'/AddOrUpdateAppointmentsResponse.php',
        'Famoser\MBOApiWrapper\AppointmentService\AddOrUpdateAppointmentsResult' => __DIR__ .'/AddOrUpdateAppointmentsResult.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetBookableItems' => __DIR__ .'/GetBookableItems.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetBookableItemsRequest' => __DIR__ .'/GetBookableItemsRequest.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetBookableItemsResponse' => __DIR__ .'/GetBookableItemsResponse.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetBookableItemsResult' => __DIR__ .'/GetBookableItemsResult.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfScheduleItem' => __DIR__ .'/ArrayOfScheduleItem.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetScheduleItems' => __DIR__ .'/GetScheduleItems.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetScheduleItemsRequest' => __DIR__ .'/GetScheduleItemsRequest.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetScheduleItemsResponse' => __DIR__ .'/GetScheduleItemsResponse.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetScheduleItemsResult' => __DIR__ .'/GetScheduleItemsResult.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfStaff' => __DIR__ .'/ArrayOfStaff.php',
        'Famoser\MBOApiWrapper\AppointmentService\AddOrUpdateAvailabilities' => __DIR__ .'/AddOrUpdateAvailabilities.php',
        'Famoser\MBOApiWrapper\AppointmentService\AddOrUpdateAvailabilitiesRequest' => __DIR__ .'/AddOrUpdateAvailabilitiesRequest.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfDayOfWeek' => __DIR__ .'/ArrayOfDayOfWeek.php',
        'Famoser\MBOApiWrapper\AppointmentService\DayOfWeek' => __DIR__ .'/DayOfWeek.php',
        'Famoser\MBOApiWrapper\AppointmentService\AvailabilityDisplay' => __DIR__ .'/AvailabilityDisplay.php',
        'Famoser\MBOApiWrapper\AppointmentService\AddOrUpdateAvailabilitiesResponse' => __DIR__ .'/AddOrUpdateAvailabilitiesResponse.php',
        'Famoser\MBOApiWrapper\AppointmentService\AddOrUpdateAvailabilitiesResult' => __DIR__ .'/AddOrUpdateAvailabilitiesResult.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetActiveSessionTimes' => __DIR__ .'/GetActiveSessionTimes.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetActiveSessionTimesRequest' => __DIR__ .'/GetActiveSessionTimesRequest.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetActiveSessionTimesResponse' => __DIR__ .'/GetActiveSessionTimesResponse.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetActiveSessionTimesResult' => __DIR__ .'/GetActiveSessionTimesResult.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfDateTime' => __DIR__ .'/ArrayOfDateTime.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetAppointmentOptions' => __DIR__ .'/GetAppointmentOptions.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetAppointmentOptionsRequest' => __DIR__ .'/GetAppointmentOptionsRequest.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetAppointmentOptionsResponse' => __DIR__ .'/GetAppointmentOptionsResponse.php',
        'Famoser\MBOApiWrapper\AppointmentService\GetAppointmentOptionsResult' => __DIR__ .'/GetAppointmentOptionsResult.php',
        'Famoser\MBOApiWrapper\AppointmentService\ArrayOfOption' => __DIR__ .'/ArrayOfOption.php',
        'Famoser\MBOApiWrapper\AppointmentService\Option' => __DIR__ .'/Option.php',
        'Famoser\MBOApiWrapper\AppointmentService\ApplyPayment' => __DIR__ .'/ApplyPayment.php',
        'Famoser\MBOApiWrapper\AppointmentService\AppointmentApplyPaymentRequest' => __DIR__ .'/AppointmentApplyPaymentRequest.php',
        'Famoser\MBOApiWrapper\AppointmentService\ApplyPaymentResponse' => __DIR__ .'/ApplyPaymentResponse.php',
        'Famoser\MBOApiWrapper\AppointmentService\AppointmentApplyPaymentResult' => __DIR__ .'/AppointmentApplyPaymentResult.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_8ff1164f949e3fd9aef489b1419e195f');

// Do nothing. The rest is just leftovers from the code generation.
{
}
