<?php


 function autoload_adce4e9acd5bd459be3c81821dcd811f($class)
{
    $classes = array(
        'Famoser\MBOApiWrapper\ClassService\Class_x0020_Service' => __DIR__ .'/Class_x0020_Service.php',
        'Famoser\MBOApiWrapper\ClassService\GetClasses' => __DIR__ .'/GetClasses.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassesRequest' => __DIR__ .'/GetClassesRequest.php',
        'Famoser\MBOApiWrapper\ClassService\MBRequest' => __DIR__ .'/MBRequest.php',
        'Famoser\MBOApiWrapper\ClassService\SourceCredentials' => __DIR__ .'/SourceCredentials.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfInt' => __DIR__ .'/ArrayOfInt.php',
        'Famoser\MBOApiWrapper\ClassService\UserCredentials' => __DIR__ .'/UserCredentials.php',
        'Famoser\MBOApiWrapper\ClassService\XMLDetailLevel' => __DIR__ .'/XMLDetailLevel.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfString' => __DIR__ .'/ArrayOfString.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfLong' => __DIR__ .'/ArrayOfLong.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassesResponse' => __DIR__ .'/GetClassesResponse.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassesResult' => __DIR__ .'/GetClassesResult.php',
        'Famoser\MBOApiWrapper\ClassService\MBResult' => __DIR__ .'/MBResult.php',
        'Famoser\MBOApiWrapper\ClassService\StatusCode' => __DIR__ .'/StatusCode.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfClass' => __DIR__ .'/ArrayOfClass.php',
        'Famoser\MBOApiWrapper\ClassService\ClassCustom' => __DIR__ .'/ClassCustom.php',
        'Famoser\MBOApiWrapper\ClassService\MBObject' => __DIR__ .'/MBObject.php',
        'Famoser\MBOApiWrapper\ClassService\Site' => __DIR__ .'/Site.php',
        'Famoser\MBOApiWrapper\ClassService\ClassDescription' => __DIR__ .'/ClassDescription.php',
        'Famoser\MBOApiWrapper\ClassService\Level' => __DIR__ .'/Level.php',
        'Famoser\MBOApiWrapper\ClassService\ActionCode' => __DIR__ .'/ActionCode.php',
        'Famoser\MBOApiWrapper\ClassService\Program' => __DIR__ .'/Program.php',
        'Famoser\MBOApiWrapper\ClassService\ScheduleType' => __DIR__ .'/ScheduleType.php',
        'Famoser\MBOApiWrapper\ClassService\SessionType' => __DIR__ .'/SessionType.php',
        'Famoser\MBOApiWrapper\ClassService\Resource' => __DIR__ .'/Resource.php',
        'Famoser\MBOApiWrapper\ClassService\ClientService' => __DIR__ .'/ClientService.php',
        'Famoser\MBOApiWrapper\ClassService\SalesRep' => __DIR__ .'/SalesRep.php',
        'Famoser\MBOApiWrapper\ClassService\Rep' => __DIR__ .'/Rep.php',
        'Famoser\MBOApiWrapper\ClassService\Staff' => __DIR__ .'/Staff.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfAppointment' => __DIR__ .'/ArrayOfAppointment.php',
        'Famoser\MBOApiWrapper\ClassService\Appointment' => __DIR__ .'/Appointment.php',
        'Famoser\MBOApiWrapper\ClassService\ScheduleItem' => __DIR__ .'/ScheduleItem.php',
        'Famoser\MBOApiWrapper\ClassService\Unavailability' => __DIR__ .'/Unavailability.php',
        'Famoser\MBOApiWrapper\ClassService\Availability' => __DIR__ .'/Availability.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfProgram' => __DIR__ .'/ArrayOfProgram.php',
        'Famoser\MBOApiWrapper\ClassService\Location' => __DIR__ .'/Location.php',
        'Famoser\MBOApiWrapper\ClassService\AppointmentStatus' => __DIR__ .'/AppointmentStatus.php',
        'Famoser\MBOApiWrapper\ClassService\Client' => __DIR__ .'/Client.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfClientIndex' => __DIR__ .'/ArrayOfClientIndex.php',
        'Famoser\MBOApiWrapper\ClassService\ClientIndex' => __DIR__ .'/ClientIndex.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfClientIndexValue' => __DIR__ .'/ArrayOfClientIndexValue.php',
        'Famoser\MBOApiWrapper\ClassService\ClientIndexValue' => __DIR__ .'/ClientIndexValue.php',
        'Famoser\MBOApiWrapper\ClassService\ClientCreditCard' => __DIR__ .'/ClientCreditCard.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfClientRelationship' => __DIR__ .'/ArrayOfClientRelationship.php',
        'Famoser\MBOApiWrapper\ClassService\ClientRelationship' => __DIR__ .'/ClientRelationship.php',
        'Famoser\MBOApiWrapper\ClassService\Relationship' => __DIR__ .'/Relationship.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfRep' => __DIR__ .'/ArrayOfRep.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfSalesRep' => __DIR__ .'/ArrayOfSalesRep.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfCustomClientField' => __DIR__ .'/ArrayOfCustomClientField.php',
        'Famoser\MBOApiWrapper\ClassService\CustomClientField' => __DIR__ .'/CustomClientField.php',
        'Famoser\MBOApiWrapper\ClassService\Liability' => __DIR__ .'/Liability.php',
        'Famoser\MBOApiWrapper\ClassService\ProspectStage' => __DIR__ .'/ProspectStage.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfResource' => __DIR__ .'/ArrayOfResource.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfUnavailability' => __DIR__ .'/ArrayOfUnavailability.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfAvailability' => __DIR__ .'/ArrayOfAvailability.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfLocation' => __DIR__ .'/ArrayOfLocation.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfProviderIDUpdate' => __DIR__ .'/ArrayOfProviderIDUpdate.php',
        'Famoser\MBOApiWrapper\ClassService\ProviderIDUpdate' => __DIR__ .'/ProviderIDUpdate.php',
        'Famoser\MBOApiWrapper\ClassService\Visit' => __DIR__ .'/Visit.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfVisit' => __DIR__ .'/ArrayOfVisit.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfClient' => __DIR__ .'/ArrayOfClient.php',
        'Famoser\MBOApiWrapper\ClassService\UpdateClientVisits' => __DIR__ .'/UpdateClientVisits.php',
        'Famoser\MBOApiWrapper\ClassService\UpdateClientVisitsRequest' => __DIR__ .'/UpdateClientVisitsRequest.php',
        'Famoser\MBOApiWrapper\ClassService\UpdateClientVisitsResponse' => __DIR__ .'/UpdateClientVisitsResponse.php',
        'Famoser\MBOApiWrapper\ClassService\UpdateClientVisitsResult' => __DIR__ .'/UpdateClientVisitsResult.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassVisits' => __DIR__ .'/GetClassVisits.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassVisitsRequest' => __DIR__ .'/GetClassVisitsRequest.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassVisitsResponse' => __DIR__ .'/GetClassVisitsResponse.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassVisitsResult' => __DIR__ .'/GetClassVisitsResult.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassDescriptions' => __DIR__ .'/GetClassDescriptions.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassDescriptionsRequest' => __DIR__ .'/GetClassDescriptionsRequest.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassDescriptionsResponse' => __DIR__ .'/GetClassDescriptionsResponse.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassDescriptionsResult' => __DIR__ .'/GetClassDescriptionsResult.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfClassDescription' => __DIR__ .'/ArrayOfClassDescription.php',
        'Famoser\MBOApiWrapper\ClassService\GetEnrollments' => __DIR__ .'/GetEnrollments.php',
        'Famoser\MBOApiWrapper\ClassService\GetEnrollmentsRequest' => __DIR__ .'/GetEnrollmentsRequest.php',
        'Famoser\MBOApiWrapper\ClassService\GetEnrollmentsResponse' => __DIR__ .'/GetEnrollmentsResponse.php',
        'Famoser\MBOApiWrapper\ClassService\GetEnrollmentsResult' => __DIR__ .'/GetEnrollmentsResult.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfClassSchedule' => __DIR__ .'/ArrayOfClassSchedule.php',
        'Famoser\MBOApiWrapper\ClassService\ClassSchedule' => __DIR__ .'/ClassSchedule.php',
        'Famoser\MBOApiWrapper\ClassService\Course' => __DIR__ .'/Course.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassSchedules' => __DIR__ .'/GetClassSchedules.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassSchedulesRequest' => __DIR__ .'/GetClassSchedulesRequest.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassSchedulesResponse' => __DIR__ .'/GetClassSchedulesResponse.php',
        'Famoser\MBOApiWrapper\ClassService\GetClassSchedulesResult' => __DIR__ .'/GetClassSchedulesResult.php',
        'Famoser\MBOApiWrapper\ClassService\AddClientsToClasses' => __DIR__ .'/AddClientsToClasses.php',
        'Famoser\MBOApiWrapper\ClassService\AddClientsToClassesRequest' => __DIR__ .'/AddClientsToClassesRequest.php',
        'Famoser\MBOApiWrapper\ClassService\AddClientsToClassesResponse' => __DIR__ .'/AddClientsToClassesResponse.php',
        'Famoser\MBOApiWrapper\ClassService\AddClientsToClassesResult' => __DIR__ .'/AddClientsToClassesResult.php',
        'Famoser\MBOApiWrapper\ClassService\RemoveClientsFromClasses' => __DIR__ .'/RemoveClientsFromClasses.php',
        'Famoser\MBOApiWrapper\ClassService\RemoveClientsFromClassesRequest' => __DIR__ .'/RemoveClientsFromClassesRequest.php',
        'Famoser\MBOApiWrapper\ClassService\RemoveClientsFromClassesResponse' => __DIR__ .'/RemoveClientsFromClassesResponse.php',
        'Famoser\MBOApiWrapper\ClassService\RemoveClientsFromClassesResult' => __DIR__ .'/RemoveClientsFromClassesResult.php',
        'Famoser\MBOApiWrapper\ClassService\AddClientsToEnrollments' => __DIR__ .'/AddClientsToEnrollments.php',
        'Famoser\MBOApiWrapper\ClassService\AddClientsToEnrollmentsRequest' => __DIR__ .'/AddClientsToEnrollmentsRequest.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfDateTime' => __DIR__ .'/ArrayOfDateTime.php',
        'Famoser\MBOApiWrapper\ClassService\AddClientsToEnrollmentsResponse' => __DIR__ .'/AddClientsToEnrollmentsResponse.php',
        'Famoser\MBOApiWrapper\ClassService\AddClientsToEnrollmentsResult' => __DIR__ .'/AddClientsToEnrollmentsResult.php',
        'Famoser\MBOApiWrapper\ClassService\RemoveFromWaitlist' => __DIR__ .'/RemoveFromWaitlist.php',
        'Famoser\MBOApiWrapper\ClassService\RemoveFromWaitlistRequest' => __DIR__ .'/RemoveFromWaitlistRequest.php',
        'Famoser\MBOApiWrapper\ClassService\RemoveFromWaitlistResponse' => __DIR__ .'/RemoveFromWaitlistResponse.php',
        'Famoser\MBOApiWrapper\ClassService\RemoveFromWaitlistResult' => __DIR__ .'/RemoveFromWaitlistResult.php',
        'Famoser\MBOApiWrapper\ClassService\GetSemesters' => __DIR__ .'/GetSemesters.php',
        'Famoser\MBOApiWrapper\ClassService\GetSemestersRequest' => __DIR__ .'/GetSemestersRequest.php',
        'Famoser\MBOApiWrapper\ClassService\GetSemestersResponse' => __DIR__ .'/GetSemestersResponse.php',
        'Famoser\MBOApiWrapper\ClassService\GetSemestersResult' => __DIR__ .'/GetSemestersResult.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfSemester' => __DIR__ .'/ArrayOfSemester.php',
        'Famoser\MBOApiWrapper\ClassService\Semester' => __DIR__ .'/Semester.php',
        'Famoser\MBOApiWrapper\ClassService\GetCourses' => __DIR__ .'/GetCourses.php',
        'Famoser\MBOApiWrapper\ClassService\GetCoursesRequest' => __DIR__ .'/GetCoursesRequest.php',
        'Famoser\MBOApiWrapper\ClassService\GetCoursesResponse' => __DIR__ .'/GetCoursesResponse.php',
        'Famoser\MBOApiWrapper\ClassService\GetCoursesResult' => __DIR__ .'/GetCoursesResult.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfCourse' => __DIR__ .'/ArrayOfCourse.php',
        'Famoser\MBOApiWrapper\ClassService\GetWaitlistEntries' => __DIR__ .'/GetWaitlistEntries.php',
        'Famoser\MBOApiWrapper\ClassService\GetWaitlistEntriesRequest' => __DIR__ .'/GetWaitlistEntriesRequest.php',
        'Famoser\MBOApiWrapper\ClassService\GetWaitlistEntriesResponse' => __DIR__ .'/GetWaitlistEntriesResponse.php',
        'Famoser\MBOApiWrapper\ClassService\GetWaitlistEntriesResult' => __DIR__ .'/GetWaitlistEntriesResult.php',
        'Famoser\MBOApiWrapper\ClassService\ArrayOfWaitlistEntry' => __DIR__ .'/ArrayOfWaitlistEntry.php',
        'Famoser\MBOApiWrapper\ClassService\WaitlistEntry' => __DIR__ .'/WaitlistEntry.php',
        'Famoser\MBOApiWrapper\ClassService\SubstituteClassTeacher' => __DIR__ .'/SubstituteClassTeacher.php',
        'Famoser\MBOApiWrapper\ClassService\SubstituteClassTeacherRequest' => __DIR__ .'/SubstituteClassTeacherRequest.php',
        'Famoser\MBOApiWrapper\ClassService\SubstituteClassTeacherResponse' => __DIR__ .'/SubstituteClassTeacherResponse.php',
        'Famoser\MBOApiWrapper\ClassService\SubstituteClassTeacherResult' => __DIR__ .'/SubstituteClassTeacherResult.php',
        'Famoser\MBOApiWrapper\ClassService\SubtituteClassTeacher' => __DIR__ .'/SubtituteClassTeacher.php',
        'Famoser\MBOApiWrapper\ClassService\SubtituteClassTeacherResponse' => __DIR__ .'/SubtituteClassTeacherResponse.php',
        'Famoser\MBOApiWrapper\ClassService\CancelSingleClass' => __DIR__ .'/CancelSingleClass.php',
        'Famoser\MBOApiWrapper\ClassService\CancelSingleClassRequest' => __DIR__ .'/CancelSingleClassRequest.php',
        'Famoser\MBOApiWrapper\ClassService\CancelSingleClassResponse' => __DIR__ .'/CancelSingleClassResponse.php',
        'Famoser\MBOApiWrapper\ClassService\CancelSingleClassResult' => __DIR__ .'/CancelSingleClassResult.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_adce4e9acd5bd459be3c81821dcd811f');

// Do nothing. The rest is just leftovers from the code generation.
{
}
